// lib/firebase_options.dart
// Generated by FlutterFire CLI - CUSTOMIZE WITH YOUR FIREBASE PROJECT DETAILS

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID_HERE',
    projectId: 'YOUR_PROJECT_ID_HERE',
    authDomain: 'YOUR_AUTH_DOMAIN_HERE',
    databaseURL: 'YOUR_DATABASE_URL_HERE',
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE',
    iosBundleId: 'com.example.healthMangoScanner',
    androidClientId: 'YOUR_ANDROID_CLIENT_ID_HERE',
  );
}
